# Generated by Django 3.0.6 on 2020-06-05 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'My Subscribers', 'verbose_name_plural': 'A lot of Subscribers'},
        ),
    ]
